#include "Arduboy2.h"

#define CATHY_3K

#ifdef CATHY_3K
    #define MAGE_TEXT_OFFSET 7
#else
    #define MAGE_TEXT_OFFSET 2
#endif

const char text_0[] PROGMEM = "I HAVE HEARD\nTHAT A FOUL AND\nPOWERFUL DEMON LURKS\nIN THE CHURCH\nYOU MUST SLAY HIM!";
const char text_1[] PROGMEM = "AS YOU DESCEND\nINTO THE LABRYINTH\nMAKE SURE TO LOOK\nAT MANY ITEMS\nSOME MAY BE MAGIC!";
const char text_2[] PROGMEM = "I HAVE SEEN MANY\nMONSTERS OF ALL FOUL\nKINDS PEEKING OUT\nFROM THE\nCHURCH.BE WARY!";
const char text_3[] PROGMEM = "I SUSPECT OUR OPPRESSORS\nHAVE COME FROM THE\nNINE INFERNAL HELLS.\nWHO KNOWS WHAT ASMORDEUS\nTHE WICKED IS UP TO NOW?";
const char text_4[] PROGMEM = "OUR BLACKSMITH HAS\nTHE BEST WEAPONS\nAND ARMOUR IN THIS FIEF!\nEVEN OUR DUKE USES\nTHEM FOR HIS ARMY!";
const char text_5[] PROGMEM = "MANY GREAT ADVENTURERS\nHAVE COME HERE BUT\nNONE HAVE COME OUT!";
const char text_6[] PROGMEM = "ONCE THE RUTHLESS SWORD\nWILL STRIKE TWICE THE EVIL\nDEMON BITES THRICE THE\nHOLY ANGEL SINGS QUADRICE\nGREAT JUDGEMENT RINGS";
const char text_7[] PROGMEM = "WISDOM IS EARNED NOT\nGIVEN. KEEP THIS IN MIND!";
const char text_8[] PROGMEM = "SOMETHING DEMONIC LIES\nIN THAT CHURCH\nMY MAGIC WILL AID\nYOU IF YOU GO IN!";
const char text_9[] PROGMEM = "CANE OUR ELDER HAS\nWISDOM THAT RIVALS\nMY OWM.TRUST\nWHAT HE SAYS!";
const char text_10[] PROGMEM = "BEWARE OF FIREBALLS!\nTHE HIGHEST RANKING\nDEMONS CAN CREATE\nTHEM AT WILL!";
const char text_11[] PROGMEM = "RAVENSGUARD LIES BETWEEN\nMT. CELESTIALS AND THE\nINFERNAL HELLS. YOU HAVE\nCOME TO A DANGEROUS\nPLACE TRAVELLER!";
const char text_12[] PROGMEM = "REJUVINATION POTIONS ARE\nTHE BEST POTIONS IN THE\nLAND. ONLY THE MOST\nPOWERFUL MONSTERS HAVE\nTHEM!";
const char text_13[] PROGMEM = "I HAVE SEEN THE\nFUTURE, YOUNG LAD.\nYOU WILL DESTROY AN\nARCHDEMON AND STABILIZE\nOUR REALM!";

const char * const npcs_text[] PROGMEM {
	text_0,
	text_1,
    text_2,
#ifdef CATHY_3K
    text_3,
    text_4,
    text_5,
    text_6,
#endif
    text_7,
    text_8,
    text_9,
#ifdef CATHY_3K
    text_10,
    text_11,
    text_12,
    text_13,
#endif
};

